const axios = require('axios').default;
const fs = require('fs').promises;
const { version } = require('./package.json');

(async () => {
  const endpointStructs = await axios({
    method: 'GET',
    url: 'https://cdn.thisnils.de/fnapicom/autogeneratedEndpointStructs.ts',
    headers: {
      'User-Agent': `fnapicom/${version}`,
    },
  });

  await fs.writeFile('./src/http/autogeneratedEndpointStructs.ts', endpointStructs.data);
})();
